name: geo-env
channels:
  - conda-forge
  - mamba
  - esri
dependencies:
  - gdal
  - geemap
  - geopandas
  - leafmap
  - localtileserver
  - pip
  - python>=3.9
  - requests
  - osmnx
  - networkx
  - arcgis
  - r-getpass
  - earthengine-api
