name: geo-env
channels:
  - conda-forge
  - mamba
  - esri
  - pypi
  - defaults
dependencies:
  - conda
  - mamba
  - osmnx
  - ca-certificates
  - certifi
  - openssl
  - ipykernel
  - python>=3.9
  - arcgis
  - geemap
  - r-getpass
  - r-base
  - r-irkernel
  - r-devtools
  - jupyter_contrib_nbextensions
  - earthengine-api
  - ipysheet
  - ipympl
  - jupyterlab
  - nodejs
  - missingno
  - geopandas
  - geopy
  - descartes
  - geojson
  - sweetviz
  - plotly_express
  - glob2
  - jupyterhub
  - gdal
  - requests
  - leafmap
  - pip
  - localtileserver
