name: geo-env
channels:
  - conda-forge
dependencies:
  - gdal
  - geemap
  - ee
  - geopandas
  - leafmap
  - localtileserver
  - pip
  - python>=3.9
  - requests
  - osmnx
  - networkx
  - arcgis
  - getpass
