name: geo-env
channels:
  - conda-forge
  - mamba
  - esri
  - pypi
dependencies:
  - gdal
  - geemap
  - geopandas
  - leafmap
  - folium
  - localtileserver
  - pip
  - python>=3.7
  - requests
  - osmnx
  - networkx
  - arcgis
  - r-getpass
  - earthengine-api
  - ipywidgets
  - ipympl 
  - jupyterlab
  - jupyterlab_widgets
  - descartes          
  - geographiclib      
  - geojson            
  - geopy
  - missingno
  - sweetviz
  - wtss
  - plotly_express
  - ipython
  - libpysal
  - mapclassify
  - cenpy
  - contextily
  - forestatrisk
  - patsy
  - pickle5
  - pywdpa
  - sklearn
  - stac
 
